export enum ACCOUNT_STATUS {
  REGISTER_UNBIND = 2,
  REGISTER_BIND = 1,
  DISABLED = 0
}

export const ACCOUNT_STATUS_LABEL = {
  [ACCOUNT_STATUS.REGISTER_UNBIND]: '注册未绑定',
  [ACCOUNT_STATUS.REGISTER_BIND]: '注册已绑定',
  [ACCOUNT_STATUS.DISABLED]: '已注销/禁用'
}

export enum ACCOUNT_REGISTER_TYPE {
  FROM_WEBSITE = 1,
  FROM_WX = 2,
  FROM_GOOGLE = 3
}

export const ACCOUNT_REGISTER_TYPE_LABEL = {
  [ACCOUNT_REGISTER_TYPE.FROM_WEBSITE]: '网站注册',
  [ACCOUNT_REGISTER_TYPE.FROM_WX]: '微信注册',
  [ACCOUNT_REGISTER_TYPE.FROM_GOOGLE]: '谷歌注册'
}